name: project_marba
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_dynamic_links: ^5.4.8
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  firebase_ui_auth: ^1.11.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  riverpod: ^2.4.9
  riverpod_annotation:
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  riverpod_generator:

flutter:
  uses-material-design: true
